In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [3]:
lung = pd.read_csv('lung_cancer_duplicate.csv')
lung.head(10)

        Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0       John         Wick   35     3.0      5       4       1
1       John  Constantine   27     NaN      2       5       1
2     Camela     Anderson   30     0.0      5       2       0
3       Alex       Telles   28     0.0      8       1       0
4      Diego     Maradona   68     NaN      5       6       1
5  Cristiano      Ronaldo   34     0.0     10       0       0
6     Mihail          Tal   58    15.0     10       0       0
7      Kathy        Bates   22     NaN      5       2       0
8     Nicole       Kidman   45     2.0      6       0       0
9        Ray      Milland   52     NaN      4       5       1

In [4]:
X=lung[['Age','Smokes','Alkhol']]
y=lung['Result']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
X

    Age  Smokes  Alkhol
0    35     3.0       4
1    27     NaN       5
2    30     0.0       2
3    28     0.0       1
4    68     NaN       6
5    34     0.0       0
6    58    15.0       0
7    22     NaN       2
8    45     2.0       0
9    52     NaN       5
10   33     4.0       0
11   18    10.0       3
12   25     2.0       1
13   28     NaN       8
14   34     NaN       8
15   39    18.0       1
16   42     NaN       5
17   19    12.0       0
18   62     5.0       3
19   73     NaN       6
20   55    15.0       3
21   33     8.0       1
22   22    20.0       2
23   44     5.0       1
24   77     3.0       6
25   21     NaN       3
26   37    15.0       2
27   34    12.0       0
28   55    20.0       4
29   40    20.0       7
30   36    13.0       2
31   56    20.0       3
32   47    15.0       8
33   62     NaN       4
34   26    10.0       2
35   25    20.0       2
36   59    20.0       4
37   62    15.0       5
38   33     NaN       2
39   37    10.0       3
40   50    20.0       4
41   47    12.0       0
42   69    20.0       4
43   63    20.0       5
44   39    15.0       2
45   21    20.0       3
46   31    20.0       4
47   28     NaN       1
48   53    20.0       3
49   62    20.0       6
50   42    12.0       2
51   44     NaN       6
52   26     NaN       8
53   35    20.0       1
54   26    13.0       1
55   77     NaN       4
56   75    15.0       5
57   43    30.0       8
58   51     NaN       0

In [35]:
from sklearn.svm import SVC
from sklearn.preprocessing import Imputer
from sklearn.pipeline import Pipeline
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp_mean=imp.fit(X_train, y_train)
imp.transform(X.values)

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

array([[35.        ,  3.        ,  4.        ],
       [27.        , 13.62068966,  5.        ],
       [30.        ,  0.        ,  2.        ],
       [28.        ,  0.        ,  1.        ],
       [68.        , 13.62068966,  6.        ],
       [34.        ,  0.        ,  0.        ],
       [58.        , 15.        ,  0.        ],
       [22.        , 13.62068966,  2.        ],
       [45.        ,  2.        ,  0.        ],
       [52.        , 13.62068966,  5.        ],
       [33.        ,  4.        ,  0.        ],
       [18.        , 10.        ,  3.        ],
       [25.        ,  2.        ,  1.        ],
       [28.        , 13.62068966,  8.        ],
       [34.        , 13.62068966,  8.        ],
       [39.        , 18.        ,  1.        ],
       [42.        , 13.62068966,  5.        ],
       [19.        , 12.        ,  0.        ],
       [62.        ,  5.        ,  3.        ],
       [73.        , 13.62068966,  6.        ],
       [55.        , 15.        ,  3.        ],
       [33.        ,  8.        ,  1.        ],
       [22.        , 20.        ,  2.        ],
       [44.        ,  5.        ,  1.        ],
       [77.        ,  3.        ,  6.        ],
       [21.        , 13.62068966,  3.        ],
       [37.        , 15.        ,  2.        ],
       [34.        , 12.        ,  0.        ],
       [55.        , 20.        ,  4.        ],
       [40.        , 20.        ,  7.        ],
       [36.        , 13.        ,  2.        ],
       [56.        , 20.        ,  3.        ],
       [47.        , 15.        ,  8.        ],
       [62.        , 13.62068966,  4.        ],
       [26.        , 10.        ,  2.        ],
       [25.        , 20.        ,  2.        ],
       [59.        , 20.        ,  4.        ],
       [62.        , 15.        ,  5.        ],
       [33.        , 13.62068966,  2.        ],
       [37.        , 10.        ,  3.        ],
       [50.        , 20.        ,  4.        ],
       [47.        , 12.        ,  0.        ],
       [69.        , 20.        ,  4.        ],
       [63.        , 20.        ,  5.        ],
       [39.        , 15.        ,  2.        ],
       [21.        , 20.        ,  3.        ],
       [31.        , 20.        ,  4.        ],
       [28.        , 13.62068966,  1.        ],
       [53.        , 20.        ,  3.        ],
       [62.        , 20.        ,  6.        ],
       [42.        , 12.        ,  2.        ],
       [44.        , 13.62068966,  6.        ],
       [26.        , 13.62068966,  8.        ],
       [35.        , 20.        ,  1.        ],
       [26.        , 13.        ,  1.        ],
       [77.        , 13.62068966,  4.        ],
       [75.        , 15.        ,  5.        ],
       [43.        , 30.        ,  8.        ],
       [51.        , 13.62068966,  0.        ]])

In [36]:
clf = SVC()
# Setup the pipeline with the required steps: steps
steps = [('imputation', Imputer(missing_values='NaN', strategy='mean', axis=0)),
        ('SVM', SVC())]

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [37]:
# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

pipeline.fit(X_train, y_train)

# Predict the labels of the test set
y_pred = pipeline.predict(X_test)

print(accuracy_score(y_test, y_pred.round()))

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.7222222222222222

In [39]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import Imputer
from sklearn.pipeline import Pipeline
imp = Imputer(missing_values='NaN', strategy='median', axis=0)
imp_mean=imp.fit(X_train, y_train)
imp.transform(X.values)

# Setup the pipeline with the required steps: steps

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

array([[35.,  3.,  4.],
       [27., 15.,  5.],
       [30.,  0.,  2.],
       [28.,  0.,  1.],
       [68., 15.,  6.],
       [34.,  0.,  0.],
       [58., 15.,  0.],
       [22., 15.,  2.],
       [45.,  2.,  0.],
       [52., 15.,  5.],
       [33.,  4.,  0.],
       [18., 10.,  3.],
       [25.,  2.,  1.],
       [28., 15.,  8.],
       [34., 15.,  8.],
       [39., 18.,  1.],
       [42., 15.,  5.],
       [19., 12.,  0.],
       [62.,  5.,  3.],
       [73., 15.,  6.],
       [55., 15.,  3.],
       [33.,  8.,  1.],
       [22., 20.,  2.],
       [44.,  5.,  1.],
       [77.,  3.,  6.],
       [21., 15.,  3.],
       [37., 15.,  2.],
       [34., 12.,  0.],
       [55., 20.,  4.],
       [40., 20.,  7.],
       [36., 13.,  2.],
       [56., 20.,  3.],
       [47., 15.,  8.],
       [62., 15.,  4.],
       [26., 10.,  2.],
       [25., 20.,  2.],
       [59., 20.,  4.],
       [62., 15.,  5.],
       [33., 15.,  2.],
       [37., 10.,  3.],
       [50., 20.,  4.],
       [47., 12.,  0.],
       [69., 20.,  4.],
       [63., 20.,  5.],
       [39., 15.,  2.],
       [21., 20.,  3.],
       [31., 20.,  4.],
       [28., 15.,  1.],
       [53., 20.,  3.],
       [62., 20.,  6.],
       [42., 12.,  2.],
       [44., 15.,  6.],
       [26., 15.,  8.],
       [35., 20.,  1.],
       [26., 13.,  1.],
       [77., 15.,  4.],
       [75., 15.,  5.],
       [43., 30.,  8.],
       [51., 15.,  0.]])

In [23]:
clf = KNeighborsClassifier()
steps = [('imputation', Imputer(missing_values='NaN', strategy='most_frequent', axis=0)),
        ('neighbors', KNeighborsClassifier())]

# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fit the pipeline to the train set
pipeline.fit(X_train, y_train)

# Predict the labels of the test set
y_pred = pipeline.predict(X_test)

# Compute metrics
print(accuracy_score(y_test, y_pred.round()))

0.8888888888888888

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [25]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import Imputer
from sklearn.pipeline import Pipeline
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp_mean=imp.fit(X_train, y_train)
imp.transform(X.values)

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

array([[35.,  3.,  4.],
       [27., 20.,  5.],
       [30.,  0.,  2.],
       [28.,  0.,  1.],
       [68., 20.,  6.],
       [34.,  0.,  0.],
       [58., 15.,  0.],
       [22., 20.,  2.],
       [45.,  2.,  0.],
       [52., 20.,  5.],
       [33.,  4.,  0.],
       [18., 10.,  3.],
       [25.,  2.,  1.],
       [28., 20.,  8.],
       [34., 20.,  8.],
       [39., 18.,  1.],
       [42., 20.,  5.],
       [19., 12.,  0.],
       [62.,  5.,  3.],
       [73., 20.,  6.],
       [55., 15.,  3.],
       [33.,  8.,  1.],
       [22., 20.,  2.],
       [44.,  5.,  1.],
       [77.,  3.,  6.],
       [21., 20.,  3.],
       [37., 15.,  2.],
       [34., 12.,  0.],
       [55., 20.,  4.],
       [40., 20.,  7.],
       [36., 13.,  2.],
       [56., 20.,  3.],
       [47., 15.,  8.],
       [62., 20.,  4.],
       [26., 10.,  2.],
       [25., 20.,  2.],
       [59., 20.,  4.],
       [62., 15.,  5.],
       [33., 20.,  2.],
       [37., 10.,  3.],
       [50., 20.,  4.],
       [47., 12.,  0.],
       [69., 20.,  4.],
       [63., 20.,  5.],
       [39., 15.,  2.],
       [21., 20.,  3.],
       [31., 20.,  4.],
       [28., 20.,  1.],
       [53., 20.,  3.],
       [62., 20.,  6.],
       [42., 12.,  2.],
       [44., 20.,  6.],
       [26., 20.,  8.],
       [35., 20.,  1.],
       [26., 13.,  1.],
       [77., 20.,  4.],
       [75., 15.,  5.],
       [43., 30.,  8.],
       [51., 20.,  0.]])

In [26]:
clf = KMeans()
steps = [('imputation', Imputer(missing_values='NaN', strategy='most_frequent', axis=0)),
        ('cluster', KMeans())]
# Create the pipeline: pipeline
pipeline = Pipeline(steps)
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Fit the pipeline to the train set
pipeline.fit(X_train, y_train)
# Predict the labels of the test set
y_pred = pipeline.predict(X_test)
# Compute metrics
print(accuracy_score(y_test, y_pred.round()))

0.3333333333333333

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [27]:
from pandas import read_csv
import numpy
from sklearn.preprocessing import Imputer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
#dataset = read_csv('lung-cancer-duplicate.csv', header=None)
# mark zero values as missing or NaN
# fill missing values with mean column values
imputer = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
transformed_X = imputer.fit_transform(X)
# evaluate an LDA model on the dataset using k-fold cross validation
imp_mean=imp.fit(X_train, y_train)
imp.transform(X.values)

C:\Users\srishti\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

array([[35.,  3.,  4.],
       [27., 20.,  5.],
       [30.,  0.,  2.],
       [28.,  0.,  1.],
       [68., 20.,  6.],
       [34.,  0.,  0.],
       [58., 15.,  0.],
       [22., 20.,  2.],
       [45.,  2.,  0.],
       [52., 20.,  5.],
       [33.,  4.,  0.],
       [18., 10.,  3.],
       [25.,  2.,  1.],
       [28., 20.,  8.],
       [34., 20.,  8.],
       [39., 18.,  1.],
       [42., 20.,  5.],
       [19., 12.,  0.],
       [62.,  5.,  3.],
       [73., 20.,  6.],
       [55., 15.,  3.],
       [33.,  8.,  1.],
       [22., 20.,  2.],
       [44.,  5.,  1.],
       [77.,  3.,  6.],
       [21., 20.,  3.],
       [37., 15.,  2.],
       [34., 12.,  0.],
       [55., 20.,  4.],
       [40., 20.,  7.],
       [36., 13.,  2.],
       [56., 20.,  3.],
       [47., 15.,  8.],
       [62., 20.,  4.],
       [26., 10.,  2.],
       [25., 20.,  2.],
       [59., 20.,  4.],
       [62., 15.,  5.],
       [33., 20.,  2.],
       [37., 10.,  3.],
       [50., 20.,  4.],
       [47., 12.,  0.],
       [69., 20.,  4.],
       [63., 20.,  5.],
       [39., 15.,  2.],
       [21., 20.,  3.],
       [31., 20.,  4.],
       [28., 20.,  1.],
       [53., 20.,  3.],
       [62., 20.,  6.],
       [42., 12.,  2.],
       [44., 20.,  6.],
       [26., 20.,  8.],
       [35., 20.,  1.],
       [26., 13.,  1.],
       [77., 20.,  4.],
       [75., 15.,  5.],
       [43., 30.,  8.],
       [51., 20.,  0.]])

In [28]:
model = LinearDiscriminantAnalysis()
kfold = KFold(n_splits=3, random_state=7)
result = cross_val_score(model, transformed_X, y, cv=kfold, scoring='accuracy')
print(result.mean())

0.9666666666666667